version: "3.7"

services:
  db:
    image: postgres:13-buster
    container_name: projectapi-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: app-prod
    image: sampalm/project-api:1.0.0
    links:
      - db
    expose: 
      - 8000
    environment:
      DB_HOST: db
    ports:
      - 8000:8000
    depends_on: 
      - db

volumes:
  postgres_data: